on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - '**'
  merge_group:
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:4
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - uses: ankane/setup-opensearch@b73d8d2d65eaa5da2add094872f12f3ae6ef1eea # v1
        with:
          opensearch-version: 2.19
      - name: Upgrade npm
        run: npm install -g npm@10
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Audit
        run: npm run audit-prod
      - name: Unit tests
        run: npm run test:unit:coverage
      - name: Wait for OpenSearch
        run: ./bin/wait-for-opensearch/run.sh
      - name: System tests
        run: npm run test:system:coverage
      - name: Run build
        run: npm run build
